FLASHSIZE   := 0
RAMSIZE     := 0

NUCLEO_ID		:= $(shell echo $(NUCLEO)|cut -c2)
NUCLEO_XID	:= NUCLEO_ID

NUCLEO_FLAGS := -D__MBED__=1

ifeq ($(NUCLEO),F303K8)
FLASHSIZE   := 65536
RAMSIZE     := 16384
CORTEXM			:= 4
LDFILE			:= STM32F303X8.ld
NUCLEO_XID	:= F303x8

NUCLEO_FLAGS += -DDEVICE_I2CSLAVE=1
NUCLEO_FLAGS += -D__FPU_PRESENT=1
NUCLEO_FLAGS += -DDEVICE_PORTOUT=1
NUCLEO_FLAGS += -DDEVICE_PORTINOUT=1
NUCLEO_FLAGS += -DTARGET_RTOS_M4_M7
NUCLEO_FLAGS += -DDEVICE_LOWPOWERTIMER=1
NUCLEO_FLAGS += -DDEVICE_RTC=1
NUCLEO_FLAGS += -DTARGET_STM32F303K8
NUCLEO_FLAGS += -DTARGET_NUCLEO_F303K8
NUCLEO_FLAGS += -D__CMSIS_RTOS
NUCLEO_FLAGS += -DTOOLCHAIN_GCC
NUCLEO_FLAGS += -DDEVICE_STDIO_MESSAGES=1
NUCLEO_FLAGS += -DDEVICE_CAN=1
NUCLEO_FLAGS += -DTARGET_CORTEX_M
NUCLEO_FLAGS += -DDEVICE_I2C_ASYNCH=1
NUCLEO_FLAGS += -DTARGET_LIKE_CORTEX_M4
NUCLEO_FLAGS += -DDEVICE_ANALOGOUT=1
NUCLEO_FLAGS += -DTARGET_M4
NUCLEO_FLAGS += -DTARGET_UVISOR_UNSUPPORTED
NUCLEO_FLAGS += -DTARGET_STM32F303x8
NUCLEO_FLAGS += -DDEVICE_SERIAL=1
NUCLEO_FLAGS += -DDEVICE_SPI_ASYNCH=1
NUCLEO_FLAGS += -DDEVICE_INTERRUPTIN=1
NUCLEO_FLAGS += -DTARGET_CORTEX
NUCLEO_FLAGS += -DDEVICE_I2C=1
NUCLEO_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
NUCLEO_FLAGS += -DRTC_LSI=1
NUCLEO_FLAGS += -D__CORTEX_M4
NUCLEO_FLAGS += -D__MBED_CMSIS_RTOS_CM
NUCLEO_FLAGS += -DTARGET_FAMILY_STM32
NUCLEO_FLAGS += -DMBED_BUILD_TIMESTAMP=1512679959.04
NUCLEO_FLAGS += -DTARGET_FF_ARDUINO
NUCLEO_FLAGS += -DDEVICE_PORTIN=1
NUCLEO_FLAGS += -DTARGET_RELEASE
NUCLEO_FLAGS += -DTARGET_STM
NUCLEO_FLAGS += -DDEVICE_SERIAL_FC=1
NUCLEO_FLAGS += -DTARGET_LIKE_MBED
NUCLEO_FLAGS += -DTARGET_STM32F3
NUCLEO_FLAGS += -DDEVICE_SLEEP=1
NUCLEO_FLAGS += -DTOOLCHAIN_GCC_ARM
NUCLEO_FLAGS += -DDEVICE_SPI=1
NUCLEO_FLAGS += -DDEVICE_SPISLAVE=1
NUCLEO_FLAGS += -DDEVICE_ANALOGIN=1
NUCLEO_FLAGS += -DDEVICE_PWMOUT=1
NUCLEO_FLAGS += -DARM_MATH_CM4
NUCLEO_FLAGS += -DTOOLCHAIN_object
NUCLEO_FLAGS += -include
NUCLEO_FLAGS +=  mbed/mbed_config.h

endif

ifeq ($(NUCLEO),F401RE)
FLASHSIZE   := 524288
RAMSIZE     := 98304
CORTEXM			:= 4
LDFILE			:= STM32F401XE.ld
NUCLEO_XID	:= F401xE

NUCLEO_FLAGS += -DDEVICE_I2CSLAVE=1
NUCLEO_FLAGS += -D__FPU_PRESENT=1
NUCLEO_FLAGS += -DDEVICE_PORTOUT=1
NUCLEO_FLAGS += -DUSBHOST_OTHER
NUCLEO_FLAGS += -DTARGET_NUCLEO_F401RE
NUCLEO_FLAGS += -DTARGET_RTOS_M4_M7
NUCLEO_FLAGS += -DDEVICE_RTC=1
NUCLEO_FLAGS += -DTOOLCHAIN_object
NUCLEO_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
NUCLEO_FLAGS += -DTARGET_STM32F4
NUCLEO_FLAGS += -D__CMSIS_RTOS
NUCLEO_FLAGS += -DTARGET_LIKE_MBED
NUCLEO_FLAGS += -DTOOLCHAIN_GCC
NUCLEO_FLAGS += -DDEVICE_I2C_ASYNCH=1
NUCLEO_FLAGS += -DTARGET_CORTEX_M
NUCLEO_FLAGS += -DTARGET_LIKE_CORTEX_M4
NUCLEO_FLAGS += -DTARGET_M4
NUCLEO_FLAGS += -DTARGET_UVISOR_UNSUPPORTED
NUCLEO_FLAGS += -DDEVICE_SPI_ASYNCH=1
NUCLEO_FLAGS += -DDEVICE_SERIAL=1
NUCLEO_FLAGS += -DDEVICE_INTERRUPTIN=1
NUCLEO_FLAGS += -DTARGET_CORTEX
NUCLEO_FLAGS += -DDEVICE_I2C=1
NUCLEO_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
NUCLEO_FLAGS += -D__CORTEX_M4
NUCLEO_FLAGS += -DDEVICE_STDIO_MESSAGES=1
NUCLEO_FLAGS += -DTARGET_STM32F401RE
NUCLEO_FLAGS += -DTARGET_FF_MORPHO
NUCLEO_FLAGS += -DTARGET_FAMILY_STM32
NUCLEO_FLAGS += -DTARGET_FF_ARDUINO
NUCLEO_FLAGS += -DDEVICE_PORTIN=1
NUCLEO_FLAGS += -DTARGET_RELEASE
NUCLEO_FLAGS += -DTARGET_STM
NUCLEO_FLAGS += -DDEVICE_SERIAL_FC=1
NUCLEO_FLAGS += -DDEVICE_PORTINOUT=1
NUCLEO_FLAGS += -DMBED_BUILD_TIMESTAMP=1512688853.08
NUCLEO_FLAGS += -D__MBED_CMSIS_RTOS_CM
NUCLEO_FLAGS += -DDEVICE_SLEEP=1
NUCLEO_FLAGS += -DTOOLCHAIN_GCC_ARM
NUCLEO_FLAGS += -DDEVICE_SPI=1
NUCLEO_FLAGS += -DUSB_STM_HAL
NUCLEO_FLAGS += -DDEVICE_SPISLAVE=1
NUCLEO_FLAGS += -DDEVICE_ANALOGIN=1
NUCLEO_FLAGS += -DDEVICE_PWMOUT=1
NUCLEO_FLAGS += -DDEVICE_FLASH=1
NUCLEO_FLAGS += -DARM_MATH_CM4
NUCLEO_FLAGS += -DTARGET_STM32F401xE
NUCLEO_FLAGS += -include
NUCLEO_FLAGS += mbed/mbed_config.h
endif

ifeq ($(FLASHSIZE),0)
VALID_TARGET		:= 0
else
  VALID_TARGET	:= 1
endif

SIZE				= arm-none-eabi-size
SIZEFMT			= $(shell $(SIZE) $(ELF)|tail -1|tr -s ' '|cut -d' ' -f2,3,4)
TEXTSIZE		= $(shell echo $(SIZEFMT)|cut -d' ' -f1)
DATASIZE		= $(shell echo $(SIZEFMT)|cut -d' ' -f2)
BSSSIZE			= $(shell echo $(SIZEFMT)|cut -d' ' -f3)
FLASH				= $(shell echo $$(($(TEXTSIZE)+$(DATASIZE))))
RAM					= $(shell echo $$(($(DATASIZE)+$(BSSSIZE))))
