#!/bin/sh

error() {
    echo>&2 $1
    exit 1
}

[ $# -ne 1 ] && error "Usage: $0 dirname";
[ $(echo $1|cut -c1) = "/" ] && dirname=$1 || dirname=../$1

mkdir $dirname || error "Error: can't create $dirname"
cp -rf . $dirname || error "Error: can't copy files"
cd $dirname
rm -rf .git Dockerfile clone README.txt || error "Error: can't clean directory"

exit 0
