set(FLASHSIZE 0)
set(RAMSIZE   0)

execute_process(COMMAND bash -c "echo ${NUCLEO}|cut -c2" OUTPUT_VARIABLE NUCLEO_ID)
string(STRIP ${NUCLEO_ID} NUCLEO_ID)

execute_process(COMMAND bash -c "echo ${NUCLEO}|cut -c1" OUTPUT_VARIABLE NUCLEO_FAMILY)
string(STRIP ${NUCLEO_FAMILY} NUCLEO_FAMILY)

set(NUCLEO_FLAGS "-D__MBED__=1")

if(${NUCLEO} MATCHES "^F303K8$")
	set(FLASHSIZE 65536)
	set(RAMSIZE   16384)
	set(CORTEXM   4)
	set(LDFILE    "STM32F303X8.ld")
	set(NUCLEO_XID F303x8)

	list(APPEND NUCLEO_FLAGS
		DEVICE_I2CSLAVE=1
		__FPU_PRESENT=1
		DEVICE_PORTOUT=1
		DEVICE_PORTINOUT=1
		TARGET_RTOS_M4_M7
		DEVICE_LOWPOWERTIMER=1
		DEVICE_RTC=1
		TARGET_STM32F303K8
		TARGET_NUCLEO_F303K8
		__CMSIS_RTOS
		TOOLCHAIN_GCC
		DEVICE_STDIO_MESSAGES=1
		DEVICE_CAN=1
		TARGET_CORTEX_M
		DEVICE_I2C_ASYNCH=1
		TARGET_LIKE_CORTEX_M4
		DEVICE_ANALOGOUT=1
		TARGET_M4
		TARGET_UVISOR_UNSUPPORTED
		TARGET_STM32F303x8
		DEVICE_SERIAL=1
		DEVICE_SPI_ASYNCH=1
		DEVICE_INTERRUPTIN=1
		TARGET_CORTEX
		DEVICE_I2C=1
		TRANSACTION_QUEUE_SIZE_SPI=2
		RTC_LSI=1
		__CORTEX_M4
		__MBED_CMSIS_RTOS_CM
		TARGET_FAMILY_STM32
		MBED_BUILD_TIMESTAMP=1512679959.04
		TARGET_FF_ARDUINO
		DEVICE_PORTIN=1
		TARGET_RELEASE
		TARGET_STM
		DEVICE_SERIAL_FC=1
		TARGET_LIKE_MBED
		TARGET_STM32F3
		DEVICE_SLEEP=1
		TOOLCHAIN_GCC_ARM
		DEVICE_SPI=1
		DEVICE_SPISLAVE=1
		DEVICE_ANALOGIN=1
		DEVICE_PWMOUT=1
		ARM_MATH_CM4
		TOOLCHAIN_object
	)
endif()

if(${NUCLEO} MATCHES "^F401CD$")
	set(FLASHSIZE 384000)
	set(RAMSIZE   98304)
	set(CORTEXM   4)
	set(LDFILE    "STM32F401XD.ld")
	set(NUCLEO_XID F401xD)
endif()

if(${NUCLEO} MATCHES "^F401RE$")
	set(FLASHSIZE 524288)
	set(RAMSIZE   98304)
	set(CORTEXM   4)
	set(LDFILE    "STM32F401XE.ld")
	set(NUCLEO_XID F401xE)

	list(APPEND NUCLEO_FLAGS
		ARM_MATH_CM4
		DEVICE_ANALOGIN=1
		DEVICE_FLASH=1
		DEVICE_I2C=1
		DEVICE_I2CSLAVE=1
		DEVICE_I2C_ASYNCH=1
		DEVICE_INTERRUPTIN=1
		DEVICE_LOWPOWERTIMER=1
		DEVICE_PORTIN=1
		DEVICE_PORTINOUT=1
		DEVICE_PORTOUT=1
		DEVICE_PWMOUT=1
		DEVICE_RTC=1
		DEVICE_SERIAL=1
		DEVICE_SERIAL_ASYNCH=1
		DEVICE_SERIAL_FC=1
		DEVICE_SLEEP=1
		DEVICE_SPI=1
		DEVICE_SPISLAVE=1
		DEVICE_SPI_ASYNCH=1
		DEVICE_STDIO_MESSAGES=1
		MBED_BUILD_TIMESTAMP=1526554211.35
		TARGET_CORTEX
		TARGET_CORTEX_M
		TARGET_FAMILY_STM32
		TARGET_FF_ARDUINO
		TARGET_FF_MORPHO
		TARGET_LIKE_CORTEX_M4
		TARGET_LIKE_MBED
		TARGET_M4
		TARGET_NUCLEO_F401RE
		TARGET_RELEASE
		TARGET_RTOS_M4_M7
		TARGET_STM
		TARGET_STM32F4
		TARGET_STM32F401RE
		TARGET_STM32F401xE
		TARGET_UVISOR_UNSUPPORTED
		TOOLCHAIN_GCC
		TOOLCHAIN_GCC_ARM
		TOOLCHAIN_object
		TRANSACTION_QUEUE_SIZE_SPI=2
		USBHOST_OTHER
		USB_STM_HAL
		__CMSIS_RTOS
		__CORTEX_M4
		__FPU_PRESENT=1
		__MBED_CMSIS_RTOS_CM
	)
endif()

if(${NUCLEO} MATCHES "^L432KC$")
	set(FLASHSIZE   262144)
	set(RAMSIZE     65536)
	set(CORTEXM     4)
	set(LDFILE      "STM32L432XX.ld")
	set(NUCLEO_XID  L432xC)

	list(APPEND NUCLEO_FLAGS
		DEVICE_I2CSLAVE=1
		__FPU_PRESENT=1
		DEVICE_PORTOUT=1
		DEVICE_PORTINOUT=1
		TARGET_RTOS_M4_M7
		DEVICE_LOWPOWERTIMER=1
		DEVICE_RTC=1
		TOOLCHAIN_object
		DEVICE_SERIAL_ASYNCH=1
		__CMSIS_RTOS
		TOOLCHAIN_GCC
		DEVICE_CAN=1
		TARGET_CORTEX_M
		DEVICE_I2C_ASYNCH=1
		TARGET_LIKE_CORTEX_M4
		DEVICE_ANALOGOUT=1
		TARGET_M4
		TARGET_UVISOR_UNSUPPORTED
		TARGET_STM32L4
		DEVICE_SPI_ASYNCH=1
		DEVICE_PWMOUT=1
		TARGET_STM32L432xC
		TARGET_CORTEX
		DEVICE_I2C=1
		TRANSACTION_QUEUE_SIZE_SPI=2
		__CORTEX_M4
		DEVICE_STDIO_MESSAGES=1
		TARGET_FAMILY_STM32
		TARGET_FF_ARDUINO
		DEVICE_PORTIN=1
		TARGET_RELEASE
		TARGET_STM
		TARGET_STM32L432KC
		DEVICE_SERIAL_FC=1
		DEVICE_TRNG=1
		TARGET_LIKE_MBED
		__MBED_CMSIS_RTOS_CM
		DEVICE_SLEEP=1
		TOOLCHAIN_GCC_ARM
		DEVICE_SPI=1
		DEVICE_INTERRUPTIN=1
		DEVICE_SPISLAVE=1
		DEVICE_ANALOGIN=1
		DEVICE_SERIAL=1
		DEVICE_FLASH=1
		TARGET_NUCLEO_L432KC
		ARM_MATH_CM4
		MBED_BUILD_TIMESTAMP=1526505441.8
	)
endif()

if(${FLASHSIZE} MATCHES "^0$")
	message(FATAL_ERROR "[sealeo/nucleo-template] Invalid target ${NUCLEO}")
endif()

add_custom_target(display_size ALL
	DEPENDS generate_bin
	COMMAND bash -c "${CMAKE_CURRENT_SOURCE_DIR}/size_info ${ELF} ${FLASHSIZE} ${RAMSIZE}")

## Nucleo variables
set(TARGET_NAME   "TARGET_NUCLEO_${NUCLEO}")
set(TARGET_ID     "TARGET_STM32${NUCLEO_FAMILY}${NUCLEO_ID}")

set(NUCLEO_TARGET   "${CMAKE_CURRENT_SOURCE_DIR}/mbed/${TARGET_NAME}")
set(NUCLEO_STM      "${NUCLEO_TARGET}/TARGET_STM")
set(NUCLEO_STM_ID   "${NUCLEO_STM}/${TARGET_ID}")
set(NUCLEO_STM_XID  "${NUCLEO_STM_ID}/TARGET_STM32${NUCLEO_XID}")
set(LINKER_SCRIPT	${NUCLEO_TARGET}/TOOLCHAIN_GCC_ARM/${LDFILE})

#file(GLOB_RECURSE MBED_OBJECTS ${NUCLEO_TARGET}/*.o)

file(GLOB_RECURSE MBED_OBJECTS ${NUCLEO_TARGET}/TOOLCHAIN_GCC_ARM/*.o)

SET_SOURCE_FILES_PROPERTIES(
	${MBED_OBJECTS}
	PROPERTIES
	EXTERNAL_OBJECT true
	GENERATED true
)
