#ifndef __MBED_CONFIG_DATA__
#define __MBED_CONFIG_DATA__

// Configuration parameters
#define MBED_CONF_PLATFORM_STDIO_BAUD_RATE          9600
#define MBED_CONF_PLATFORM_DEFAULT_SERIAL_BAUD_RATE 9600
#define MBED_CONF_PLATFORM_STDIO_FLUSH_AT_EXIT      1
#define MBED_CONF_PLATFORM_STDIO_CONVERT_NEWLINES   0

#endif
