#!/bin/sh

error() {
	echo>&2 "${1}"
	exit 1
}

[ $# -ne 1 ] && error "Usage: ${0} ProjectName\nUsage: ${0} ProjectDirectory";
_dname=${1}
[ "$(echo "${1}"|tr -dc /|wc -c)" -eq 0 ] && _dname=../${1}
dname=$(readlink -f "${_dname}")
[ -d "${dname}" ] && error "Error: directory ${dname} already exists"

mkdir -p "${dname}" || error "Error: cannot create ${dname}"

cp -Trf mbed "${dname}/mbed"
cp -f CMakeLists.txt "${dname}/"
cp -f targets.cmake "${dname}/"
cp -f size_info "${dname}/"
cp -f tools/dmake "${dname}/"

cp -Trf src "${dname}/src"
cp -f .gitignore "${dname}/"
cp -f Doxyfile "${dname}/"
mkdir "${dname}/inc" "${dname}/lib"

echo "Info: project created in ${dname}"

exit 0
