#!/bin/bash

# Configuration
## Docker image
image=sealeo/nucleo-template

## Make tool (make or cmake)
tool=make

## Project info
projectname=$(basename $(pwd))
srcdir="src"
builddir="build"

# Script
while getopts ":l:" opt; do
	case "${opt}" in
		l)
			MOUNT_OPTS="-v ${OPTARG}/${srcdir}:$(pwd)/${projectname}/${srcdir}/$(basename ${OPTARG})"
			;;
	esac
done

shift $((OPTIND-1))

if [ "${tool}" = "cmake" ]; then
	script="mkdir -p $(pwd)/${projectname}/${builddir}; cd $(pwd)/${projectname}/${builddir}; cmake -DCMAKE_BUILD_TYPE=Release ..; make ${@}; chown 2>/dev/null -R ${USER}: $(pwd)/${projectname}/${builddir}"
else
	script="cd $(pwd)/${projectname}; make ${@}; chown 2>/dev/null -R ${USER}: $(pwd)/${projectname}/${builddir}"
fi

docker run --rm --privileged -v /etc/passwd:/etc/passwd:ro -v /dev:/dev -v $(pwd):$(pwd)/${projectname} $MOUNT_OPTS "${image}" /bin/bash -c "${script}"
