#!/bin/bash

# Configuration
## Docker image
image=sealeo/nucleo-template

## Make tool (make or cmake)
tool=cmake
buildtype=Release

## Project info
srcdir="src"
builddir="build"
mount_opts=""

# Script
mount_opts="${mount_opts} -v /etc/passwd:/etc/passwd:ro -v /dev:/dev -v $(pwd):$(pwd)"

if [ "${tool}" = "cmake" ]; then
	script="mkdir -p $(pwd)/${builddir}; cd $(pwd)/${builddir}; cmake -DCMAKE_BUILD_TYPE=${buildtype}..; make $*; chown 2>/dev/null -R ${USER}: $(pwd)/${builddir}"
else
	script="cd $(pwd); make $*; chown 2>/dev/null -R ${USER}: $(pwd)/${builddir}"
fi

docker run --rm -it --privileged ${mount_opts} "${image}" /bin/bash -c "${script}"
