#!/bin/sh

error() {
    echo>&2 $1
    exit 1
}

uddocker=n

echo -n "Warning: this will erase your projects' Makefile. Continue anyway? [y/N] "
read ask
[ "$ask" != y ] && error quit

if [ $# -eq 0 ]; then
    echo -n "Update Docker? [Y/n] "
    read uddocker

    echo -n "Type a list of projects to update: "
    read projects
else
    projects=$*
fi

[ "$uddocker" != n ] && docker build --rm -t nucleo .

for project in $projects; do 
    dname=$project
    [ ! -d "$project" ] && dname=../$project
    [ ! -d "$dname" ] && error "Error: project $project not found"

    make -C $dname purge
    rm -rf $dname/mbed $dname/.*.mk $dname/.memory $dname/[Mm]akefile
    cp -rf mbed $dname/
    cp .mbed.mk $dname/
    cp Makefile $dname/
done
exit 0
