#!/bin/bash

set -x

help() {
	echo -e "Usage:\n\n    \e[01m$0 <address>:<port>\e[00m\n"
	echo '<address> the IP or hostname of the GDB server'
	echo '<port>    the TCP port of the GDB server'
	echo
	echo "Example: $0 172.34.6.2:3444"
	exit $1
}


[ -z "$1" ] && help 1
echo "$1" | grep -Eq '[^:]+:[^:]+' || help 2

root='.'
gdb_cfg_file=$(mktemp /tmp/gdb_cfg_XXXXXXXX)
bin_file=$(make print-bin)
src_dir="$root/src"
gdb='arm-none-eabi-gdb'

cat <<EOF >$gdb_cfg_file
target remote $1
EOF

cgdb -d $gdb -- -d $src_dir -ex "target remote $1" $bin_file 
rm $gdb_cfg_file
