#!/bin/bash

help() {
	echo -e "Usage:\n\n    \e[01m$0 <address>:<port>\e[00m\n"
	echo '<address> the IP or hostname of the GDB server'
	echo '<port>    the TCP port of the GDB server'
	echo
	echo "Example: $0 172.34.6.2:3444"
	exit $1
}


[ -z "$1" ] && help 1
echo "$1" | grep -Eq '[^:]+:[^:]+' || help 2

root='.'
bin_file=$(make print-bin)
src_dir="$root/src"
gdb='arm-none-eabi-gdb'

cgdb -d $gdb -- -d $src_dir -ex "target remote $1" $bin_file 
