#!/bin/sh

error() {
	echo>&2 "$1"
	exit 1
}

uddocker=n

if [ "$#" -eq 0 ]; then
	echo -n "Update Docker? [Y/n] "
	read -r uddocker

	echo -n "Type a list of projects to update: "
	read -r projects
else
	projects=$*
fi

[ "${uddocker}" != n ] && docker pull sealeo/nucleo-template

for project in ${projects}; do
	dname=${project}
	[ ! -d "${project}" ] && dname=../${project}
	[ ! -d "${dname}" ] && error "Error: project ${project} not found"

	cp -Trf mbed "${dname}/mbed"
	cp -f targets.cmake "${dname}/"
	cp -f size_info "${dname}/"
done

echo "Warning: CMakeLists.txt and dmake not updated! Think about checking out new version"
exit 0
