#!/bin/sh

error() {
    echo>&2 $1
    exit 1
}

[ $# -ne 1 ] && error "Usage: $0 dirname";
[ $(echo $1|cut -c1) = "/" ] && dirname=$1 || dirname=../$1
[ ! -d $dirname ] && error "$dirname does not exist"

make -C $dirname purge
rm -rf $dirname/mbed
cp -rf mbed $dirname

rm -f $dirname/.mbed.mk
cp .mbed.mk $dirname

echo "Warning: main makefile not updated! Think about checking out new version"

exit 0
